[package]
name = "fire_prev_server"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
ws = { package = "rocket_ws", version = "0.1.1" }
serde = { version = "1.0", features = ["derive"] }
redis = "0.32.7"
lazy_static = "1.5.0"